const itemLists = {
    carnivalofsouls: [
        { name: "Spectral Bonehound", link: "https://www.deviantart.com/nemeionadmin/art/Spectral-Bonehound-Undead-893784851", weight: 8 },
        { name: "Fiendish Battle Wounds", link: "https://www.deviantart.com/nemeionadmin/art/Fiendish-Battle-Wounds-893643237", weight: 10 },
        { name: "Mysterious Chest", link: "https://www.deviantart.com/nemeionadmin/art/Mysterious-Chest-893646729", weight: 5 },
        { name: "Cryptic Curse", link: "https://www.deviantart.com/nemeionadmin/art/Cryptic-Curse-990293796", weight: 6 },
        { name: "Wereworm Companion", link: "https://www.deviantart.com/nemeionadmin/art/Wereworm-Companion-999723203", weight: 1 },
        { name: "Blistering Bile", link: "https://www.deviantart.com/nemeionadmin/art/Blistering-Bile-1137290581", weight: 2 },
        { name: "Bag of Teeth", link: "https://www.deviantart.com/nemeionadmin/art/Bag-of-Teeth-1150590638", weight: 5 },
        { name: "Petrified Bat", link: "https://www.deviantart.com/nemeionadmin/art/Petrified-Bat-1247918256", weight: 50 },
        { name: "Bundle of Bones", link: "https://www.deviantart.com/nemeionadmin/art/Bundle-of-Bones-1247918811", weight: 50 },
        { name: "Cursed Tome", link: "https://www.deviantart.com/nemeionadmin/art/Cursed-Tome-1247920198", weight: 4 },
        { name: "Mark of the Gorgon", link: "https://www.deviantart.com/nemeionadmin/art/Mark-of-the-Gorgon-1247921681", weight: 1 },
        { name: "Stygian Sting", link: "https://www.deviantart.com/nemeionadmin/art/Stygian-Sting-1247922969", weight: 1 },
        { name: "Freakish Fangs", link: "https://www.deviantart.com/nemeionadmin/art/Freakish-Fangs-1247924583", weight: 3 },
        { name: "Lycan Companion", link: "https://www.deviantart.com/nemeionadmin/art/Lycan-Black-1247931571", weight: 5 },
        { name: "Medusa's Malice", link: "https://www.deviantart.com/nemeionadmin/art/Medusa-s-Malice-1247936681", weight: 1 },
        { name: "Bird Skull", link: "https://www.deviantart.com/nemeionadmin/art/Bird-Skull-862973254", weight: 80 },
        { name: "Jawbone", link: "https://www.deviantart.com/nemeionadmin/art/Jawbone-862975159", weight: 40 },
        { name: "Bear Skull", link: "https://www.deviantart.com/nemeionadmin/art/Bear-Skull-893640286", weight: 50 },
        { name: "Bull Skull", link: "https://www.deviantart.com/nemeionadmin/art/Bull-Skull-893641048", weight: 30 },
        { name: "Crocodile Skull", link: "https://www.deviantart.com/nemeionadmin/art/Crocodile-Skull-893642208", weight: 50 },
        { name: "Deer Skull", link: "https://www.deviantart.com/nemeionadmin/art/Deer-Skull-893642500", weight: 60 },
        { name: "Horse Skull", link: "https://www.deviantart.com/nemeionadmin/art/Horse-Skull-893645066", weight: 50 },
        { name: "Human Skull", link: "https://www.deviantart.com/nemeionadmin/art/Human-Skull-893645114", weight: 20 },
        { name: "Lion Skull", link: "https://www.deviantart.com/nemeionadmin/art/Lion-Skull-893645738", weight: 50 },
        { name: "Rhinoceros Skull", link: "https://www.deviantart.com/nemeionadmin/art/Rhinoceros-Skull-893647731", weight: 30 },
        { name: "Cat Skull", link: "https://www.deviantart.com/nemeionadmin/art/Cat-Skull-937795740", weight: 20 },
        { name: "Bone Shards", link: "https://www.deviantart.com/nemeionadmin/art/Bone-Shards-862973354", weight: 70 },
        { name: "Bone", link: "https://www.deviantart.com/nemeionadmin/art/Bone-862973459", weight: 60 },
        { name: "Fish Bones", link: "https://www.deviantart.com/nemeionadmin/art/Fish-Bones-893643309", weight: 80 },
        { name: "Spooky Forest Background", link: "https://www.deviantart.com/nemeionadmin/art/Import-Background-Spooky-Forest-Halloween-2020-861002050", weight: 50 },
        { name: "Haunted Cage Background", link: "https://www.deviantart.com/nemeionadmin/art/Import-Background-Haunted-Cage-861788466", weight: 50 },
        { name: "Appalling Soup", link: "https://www.deviantart.com/nemeionadmin/art/Appalling-Soup-1179756715", weight: 10 },
        { name: "Befuddling Brew", link: "https://www.deviantart.com/nemeionadmin/art/Befuddling-Brew-1156343809", weight: 2 },
        { name: "Tarantula Companion", link: "https://www.deviantart.com/nemeionadmin/art/Tarantula-Redknee-1161328320", weight: 3 },
        { name: "Apple Core", link: "https://www.deviantart.com/nemeionadmin/art/Apple-Core-1149004327", weight: 70 },
        { name: "Dreadful Drought", link: "https://www.deviantart.com/nemeionadmin/art/Dreadful-Drought-1048414234", weight: 3 },
        { name: "Ancient Tablet", link: "https://www.deviantart.com/nemeionadmin/art/Ancient-Tablet-1048407956", weight: 5 },
        { name: "Cerberus Companion", link: "https://www.deviantart.com/nemeionadmin/art/Cerberus-Black-1048406109", weight: 6 },
        { name: "Rhodochrosite", link: "https://www.deviantart.com/nemeionadmin/art/Rhodochrosite-937796180", weight: 20 },
        { name: "Warpaints", link: "https://www.deviantart.com/nemeionadmin/art/Warpaints-893785368", weight: 5 },
        { name: "Small Pile of Coins", link: "https://www.deviantart.com/nemeionadmin/art/Small-Pile-of-Coins-893784355", weight: 50 },
        { name: "Pumpkin", link: "https://www.deviantart.com/nemeionadmin/art/Pumpkin-893647256", weight: 50 },
        { name: "Leaves", link: "https://www.deviantart.com/nemeionadmin/art/Leaves-893645383", weight: 50 },
        { name: "Eyeball", link: "https://www.deviantart.com/nemeionadmin/art/Eyeball-893642973", weight: 30 },
        { name: "Cloth", link: "https://www.deviantart.com/nemeionadmin/art/Cloth-893641617", weight: 30 },
        { name: "Facade of the Caesar", link: "https://www.deviantart.com/nemeionadmin/art/Facade-of-the-Caesar-795624271", weight: 5 },
        { name: "Chain", link: "https://www.deviantart.com/nemeionadmin/art/Chain-862973515", weight: 20 }
    ],
    feastoffools: [
        { name: "Bag of Gags", link: "https://www.deviantart.com/nemeionadmin/art/Bag-of-Gags-1178225699", weight: 50 },
        { name: "Doubloons", link: "https://www.deviantart.com/nemeionadmin/art/Fool-s-Doubloon-1037696568", weight: 90 },
        { name: "Festival Grounds Background", link: "https://www.deviantart.com/nemeionadmin/art/Import-Background-Festival-Grounds-1178244929", weight: 20 },
        { name: "Sailing Seas Background", link: "https://www.deviantart.com/nemeionadmin/art/Exclusive-Background-Sailing-Seas-1047716790", weight: 10 },
        { name: "Feathered Fool", link: "https://www.deviantart.com/nemeionadmin/art/Feathered-Fool-White-1106831419", weight: 10 },
        { name: "Large Sack of Coins", link: "https://www.deviantart.com/nemeionadmin/art/Large-Sack-of-Coins-893645563", weight: 70 },
        { name: "Warpaints", link: "https://www.deviantart.com/nemeionadmin/art/Warpaints-893785368", weight: 15 },
        { name: "Caesar's Dice", link: "https://www.deviantart.com/nemeionadmin/art/The-Caesar-s-dice-795623961", weight: 5 },
        { name: "Jack in the Box", link: "https://www.deviantart.com/nemeionadmin/art/Jack-in-the-Box-1178235560", weight: 2 },
        { name: "Zesty Soup",link: "https://www.deviantart.com/nemeionadmin/art/Zesty-Soup-1178930757", weight: 10 },
        { name: "Meaty Soup",link: "https://www.deviantart.com/nemeionadmin/art/Meaty-Soup-1178928074", weight: 10 },
        { name: "Questionable Soup", link: "https://www.deviantart.com/nemeionadmin/art/Questionable-Soup-1178927697", weight: 10 },
        { name: "Hearty Soup",link: "https://www.deviantart.com/nemeionadmin/art/Hearty-Soup-1178925574", weight: 10 },
        { name: "Frightening Soup", link: "https://www.deviantart.com/nemeionadmin/art/Frightening-Soup-1178924014", weight: 10 },
        { name: "Fragrant Soup", link: "https://www.deviantart.com/nemeionadmin/art/Fragrant-Soup-1178922930", weight: 10 },
        { name: "Sinister Soup", link: "https://www.deviantart.com/nemeionadmin/art/Sinister-Soup-1179741547", weight: 5 },
        { name: "Savory Soup", link: "https://www.deviantart.com/nemeionadmin/art/Savory-Soup-1179750727", weight: 10 },
        { name: "Fishy Soup", link: "https://www.deviantart.com/nemeionadmin/art/Fishy-Soup-1179751588", weight: 10 },
        { name: "Appalling Soup", link: "https://www.deviantart.com/nemeionadmin/art/Appalling-Soup-1179756715", weight: 10 },
        { name: "Feathers", link: "https://www.deviantart.com/nemeionadmin/art/Feathers-862973997", weight: 50 }
    ],
    harvestfestival: [
        { name: "Bountiful Harvest", link: "https://www.deviantart.com/nemeionadmin/art/Bountiful-Harvest-1225138578", weight: 35 },
        { name: "Pumpkin Patch", link: "https://www.deviantart.com/nemeionadmin/art/Import-Background-Pumpkin-Patch-1225141158", weight: 35 },
        { name: "Pumpkin", link: "https://www.deviantart.com/nemeionadmin/art/Pumpkin-893647256", weight: 75 },
        { name: "Bell Pepper", link: "https://www.deviantart.com/nemeionadmin/art/Bell-Pepper-1167336607", weight: 80 },
        { name: "Carrot", link: "https://www.deviantart.com/nemeionadmin/art/Carrot-1167342943", weight: 80 },
        { name: "Figs", link: "https://www.deviantart.com/nemeionadmin/art/Figs-893643273", weight: 60 },
        { name: "Berry Tart", link: "https://www.deviantart.com/nemeionadmin/art/Rustic-Berry-Tart-1225106431", weight: 5 },
        { name: "Pear Cake", link: "https://www.deviantart.com/nemeionadmin/art/Athenian-Pear-Cake-1225103429", weight: 5 },
        { name: "Torta de Pistachio", link: "https://www.deviantart.com/nemeionadmin/art/Torta-de-Pistachio-1225107002", weight: 3 },
        { name: "Savory Ribs", link: "https://www.deviantart.com/nemeionadmin/art/Savory-Ribs-1225108019", weight: 2 },
        { name: "Hardboiled Eggs", link: "https://www.deviantart.com/nemeionadmin/art/Hardboiled-Eggs-1225109071", weight: 6 },
        { name: "Peacock", link: "https://www.deviantart.com/nemeionadmin/art/Perfectly-Roasted-Peacock-1225110252", weight: 2 },
        { name: "Visciole", link: "https://www.deviantart.com/nemeionadmin/art/Torta-di-Visciole-1225111678", weight: 2 },
        { name: "Beef Souvlaki", link: "https://www.deviantart.com/nemeionadmin/art/Beef-Souvlaki-1225113188", weight: 2 },
        { name: "Fish Souvlaki", link: "https://www.deviantart.com/nemeionadmin/art/Fish-Souvlaki-1225135463", weight: 2 },
        { name: "Chicken Souvlaki", link: "https://www.deviantart.com/nemeionadmin/art/Chicken-Souvlaki-1225136749", weight: 2 },
        { name: "Pork Souvlaki", link: "https://www.deviantart.com/nemeionadmin/art/Pork-Souvlaki-1225137658", weight: 2 },
        { name: "Junk Mail", link: "https://www.deviantart.com/nemeionadmin/art/Junk-Mail-1167801625", weight: 50 },
        { name: "Pear", link: "https://www.deviantart.com/nemeionadmin/art/Pear-893647071", weight: 75 }
    ],
    seasonoflove: [
        { name: "Sloth Bron", link: "https://www.deviantart.com/nemeionadmin/art/Sloth-Bron-1154187029", weight: 2 },
        { name: "Sloth Toby", link: "https://www.deviantart.com/nemeionadmin/art/Sloth-Toby-1154184952", weight: 2 },
        { name: "Sloth Petals", link: "https://www.deviantart.com/nemeionadmin/art/Sloth-Petals-1154184152", weight: 2 },
        { name: "Sloth Figgy", link: "https://www.deviantart.com/nemeionadmin/art/Sloth-Figgy-1154183493", weight: 2 },
        { name: "Star Ruby", link: "https://www.deviantart.com/nemeionadmin/art/Star-Ruby-869944706", weight: 1 },
        { name: "Grapes", link: "https://www.deviantart.com/nemeionadmin/art/Grapes-893644172", weight: 9 },
        { name: "Stone Idol", link: "https://www.deviantart.com/nemeionadmin/art/Stone-Idol-862974823", weight: 6 },
        { name: "Aphrodite's Lament", link: "https://www.deviantart.com/nemeionadmin/art/Aphrodite-s-Lament-1048409662", weight: 4 },
        { name: "Elixir of Adonis", link: "https://www.deviantart.com/nemeionadmin/art/Elixir-of-Adonis-893642824", weight: 5 },
        { name: "Aphrodite's Passion", link: "https://www.deviantart.com/nemeionadmin/art/Aphrodite-s-Passion-893639756", weight: 4 },
        { name: "Blossom of Chloris", link: "https://www.deviantart.com/nemeionadmin/art/Blossom-of-Chloris-668240785", weight: 7 },
        { name: "Pegasus Black", link: "https://www.deviantart.com/nemeionadmin/art/Pegasus-Black-1048403355", weight: 1 },
        { name: "Pegasus Palamino", link: "https://www.deviantart.com/nemeionadmin/art/Pegasus-Palamino-1048403236", weight: 1 },
        { name: "Regal Potion", link: "https://www.deviantart.com/nemeionadmin/art/Regal-Potion-893647659", weight: 5 },
        { name: "Pegasus Piebald", link: "https://www.deviantart.com/nemeionadmin/art/Pegasus-Piebald-1048403031", weight: 1 },
        { name: "Pegasus White", link: "https://www.deviantart.com/nemeionadmin/art/Pegasus-White-1048400580", weight: 1 },
        { name: "Lost Brute Cub", link: "https://www.deviantart.com/nemeionadmin/art/Lost-Brute-Cub-893645778", weight: 6 },
        { name: "Lost Regal Cub", link: "https://www.deviantart.com/nemeionadmin/art/Lost-Regal-Cub-893645840", weight: 5 },
        { name: "Tincture of Transformation", link: "https://www.deviantart.com/nemeionadmin/art/Tincture-of-Transformation-937796429", weight: 3 },
        { name: "Brute Potion", link: "https://www.deviantart.com/nemeionadmin/art/Brute-Potion-893641009", weight: 5 },
        { name: "Sunflower", link: "https://www.deviantart.com/nemeionadmin/art/Sunflower-990294836", weight: 10 },
        { name: "Unicorn Meat", link: "https://www.deviantart.com/nemeionadmin/art/Unicorn-Meat-1037691492", weight: 2 },
        { name: "Fields of Love", link: "https://www.deviantart.com/nemeionadmin/art/Import-Background-Fields-of-Love-1154191432", weight: 9 },
        { name: "Sloth Charlie", link: "https://www.deviantart.com/nemeionadmin/art/Sloth-Charlie-1154181335", weight: 4 }
    ],
     harvestfestivalcurrency: [
        { name: "Corn", link: "https://www.deviantart.com/nemeionadmin/art/Corn-1167334952", weight: 99 }
    ],
    carnivalofsoulscurrency: [
        { name: "Scales", link: "https://www.deviantart.com/nemeionadmin/art/Scales-1247922448", weight: 25 },
        { name: "Teeth", link: "https://www.deviantart.com/nemeionadmin/art/Teeth-857006414", weight: 75 }
    ],
    feastoffoolscurrency: [
        { name: "Doubloons", link: "https://www.deviantart.com/nemeionadmin/art/Corn-1167334952", weight: 99 }
    ],
    seasonoflovecurrency: [
        { name: "Flowers", link: "https://www.deviantart.com/nemeionadmin/art/Corn-1167334952", weight: 99 }
    ],
};

